version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Hub 
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: 
          name: Build Image 
          command: |
            docker build -t $PUBLISHED_IMAGE_NAME:$CIRCLE_SHA1 -t $PUBLISHED_IMAGE_NAME:latest .
      - run: 
          name: Push to Docker Hub 
          command: |
            docker push $PUBLISHED_IMAGE_NAME:$CIRCLE_SHA1
            docker push $PUBLISHED_IMAGE_NAME:latest
